export type VerificationTarget = { readonly repository: string; readonly pullRequestNumber: number; readonly baseSha: string; readonly headSha: string; readonly targetScopeId: string };
export type VerificationCommand = { readonly name: string; readonly run: string; readonly timeoutMinutes?: number };
export type IsolationAttestation = { readonly backend: "GITHUB_HOSTED_LINUX_SANDBOX_V1"; readonly attested: true; readonly platform?: string; readonly enforcesFilesystem?: boolean; readonly enforcesNetwork?: boolean; readonly enforcesProcessTreeTermination?: boolean; readonly filesystemRoot?: string };
export type ExecutionBoundary = { readonly id: string; readonly maximumCommandCount: number; readonly maximumCommandTimeoutSeconds: number; readonly maximumTotalTimeoutSeconds: number; readonly maximumOutputBytesPerStream: number; readonly maximumPreviewBytesPerStream: number; readonly terminateProcessTree: true; readonly allowedEnvironmentNames: readonly string[]; readonly deniedEnvironmentNames: readonly string[]; readonly networkPolicy?: string; readonly filesystemPolicy?: string; readonly filesystemRoot?: string; readonly approvedShellPath?: string; readonly allowedShellPaths?: readonly string[]; readonly shellSha256?: string; readonly executableSha256?: string; readonly targetIdentity?: VerificationTarget; readonly terminationGraceMilliseconds?: number; readonly terminationKillMilliseconds?: number; readonly terminationMonitorMilliseconds?: number };
export type AuthorityLineage = { readonly trustedConfigurationSha256: string; readonly policySha256: string; readonly evidenceContractSha256: string };
export type RunnerIdentity = { readonly runner: string; readonly os: string; readonly architecture: string; readonly node: string };
export type VerificationClock = { readonly now: () => Date };
export type VerificationRunnerOptions = { readonly target: VerificationTarget; readonly commands: readonly VerificationCommand[]; readonly workingDirectory: string; readonly shellPath: string; readonly executionBoundary: ExecutionBoundary; readonly authorityLineage: AuthorityLineage; readonly marketConfigSha256: string; readonly isolationAttestation: IsolationAttestation; readonly controlEnvironment?: Readonly<Record<string, string | undefined>>; readonly clock?: VerificationClock; readonly runnerIdentity?: RunnerIdentity };
export type VerificationStatus = "PASS" | "FAIL" | "TIMEOUT" | "ERROR";
export type VerificationReceipt = { readonly schemaVersion: "proofrail.verification-receipt.v1"; readonly id: string; readonly type: "COMMAND_EXECUTION"; readonly producer: { readonly id: "runner.proofrail-verification"; readonly version: "1.0.0" }; readonly target: VerificationTarget; readonly command: { readonly name: string; readonly run: string; readonly orderingKey: string }; readonly environment: RunnerIdentity & { readonly allowedEnvironmentNames: readonly string[] }; readonly executionBoundaryId: string; readonly timing: { readonly startedAt: string; readonly endedAt: string; readonly durationMs: number }; readonly result: { readonly status: VerificationStatus; readonly exitCode: number | null; readonly stdoutDigest: string; readonly stderrDigest: string; readonly stdoutBytes: number; readonly stderrBytes: number; readonly stdoutPreview: string; readonly stderrPreview: string; readonly stdoutTruncated: boolean; readonly stderrTruncated: boolean; readonly timedOut: boolean }; readonly dependencyLockfile: { readonly path: string | null; readonly sha256: string | null }; readonly redaction: { readonly applied: boolean; readonly matchCount: number }; readonly lineage: AuthorityLineage & { readonly marketConfigSha256: string } };
export type VerificationRunnerErrorCode = "INVALID_OPTIONS" | "LOCKFILE_READ_FAILED" | "BLOCKED_EXECUTION_BOUNDARY" | "PROCESS_TERMINATION_FAILED";
export class VerificationRunnerError extends Error { readonly name: "VerificationRunnerError"; readonly code: VerificationRunnerErrorCode; constructor(code: VerificationRunnerErrorCode, message: string, options?: ErrorOptions); }
export function runVerificationPlan(options: VerificationRunnerOptions): Promise<readonly VerificationReceipt[]>;
