// @ts-check

export const PHASE1_KERNEL_INPUT_SCHEMA_VERSION = "proofrail.kernel.input.phase1.v1";
export const PHASE1_BUNDLE_SCHEMA_VERSION = "proofrail.evidence-bundle.phase1.v1";
export const PHASE1_KERNEL_ENGINE_VERSION = "0.1.0-phase1";

export const VERDICTS = Object.freeze([
  "ADMISSIBLE",
  "REVISION_REQUIRED",
  "REJECTED",
  "BLOCKED"
]);

export const EVIDENCE_CONTRACT_SELECTION_PROVENANCE_SOURCES = Object.freeze([
  "TRUSTED_CONFIGURATION",
  "DETERMINISTIC_POLICY_SELECTION"
]);

export const RULE_AUTHORITY_PROVENANCE_SOURCES = Object.freeze([
  "TRUSTED_CONFIGURATION",
  "POLICY"
]);

export const EVIDENCE_SATISFACTION_KIND = "OBSERVATION_FACT_EQUALS";

export const RULE_PREDICATES = Object.freeze([
  "EVIDENCE_PRESENT",
  "EVIDENCE_ABSENT"
]);

export const RULE_EFFECT_DENY = "DENY";

export const MARKET_KERNEL_INPUT_SCHEMA_VERSION = "proofrail.kernel.input.v2";
export const MARKET_KERNEL_BUNDLE_SCHEMA_VERSION = "proofrail.evidence-bundle.v2";
export const MARKET_KERNEL_ENGINE_VERSION = "0.3.0-market-prototype";
export const MARKET_REQUIREMENT_INPUT_KINDS = Object.freeze(["OBSERVATION", "VERIFICATION_RECEIPT"]);
export const VERIFICATION_RECEIPT_STATUSES = Object.freeze(["PASS", "FAIL", "TIMEOUT", "ERROR"]);
export const MARKET_POLICY_CONDITIONS = Object.freeze([
  "STALE_TARGET",
  "EXECUTION_IMPOSSIBLE",
  "SCOPE_PATH_DENIED",
  "UNTRUSTED_POLICY_CHANGE",
  "VERIFICATION_COMMAND_FAILED",
  "EXACT_HEAD_APPROVAL_MISSING",
  "MINIMUM_APPROVALS_MISSING",
  "CHANGES_REQUESTED_PRESENT",
  "REPORTED_CHECK_FAILED",
  "REQUIRED_EVIDENCE_MISSING"
]);
